### ISSUE TITLE
collapse 2020a branch into develop

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-easyconfigs#10753]
We still need to collapse some easyconfigs that got merged into the `2020a` branch but are not included in `develop` yet (see for example #10108).

That didn't happen shortly before the EasyBuild v4.2.1 release due to the `MPI_Init` issue with `h5py` (which is resolved now thanks to #10626).

* [x] dtcmp 1.1.0 (~~#10110~~ -> ~~#10895~~)
* [x] HDF5 1.12.0 (~~#10131~~ -> ~~#10892~~)
* [x] lwgrp (~~#10108~~ -> ~~#10894~~)
* [x] ParaView 5.8.0 (~~#10369~~ -> ~~#10890~~)
* [x] PETSc 3.12.4 (~~#10532~~)
* [x] Scalasca 2.5 (+ Score-P, Cube*, OTF2, OPARI2, PAPI, PDT, SIONlib) (~~#10421~~ -> ~~#10893~~)
* [x] `libxsmm-1.15-intel-2020a.eb` -> `libxsmm-1.16.1-iccifort-2020.1.217.eb` (~~#10714~~)
  * incl. `libxc-4.3.4-iccifort-2020.1.217.eb`
* [x] `Libint-2.6.0-iimpi-2020a.eb` (replaced with `Libint-2.6.0-iimpi-2020a-lmax-6-cp2k.eb`, see ~~#11099~~)
* [x] `OpenMPI-4.0.3-GCC-9.2.0.eb` (replaced with `OpenMPI-4.0.3-GCC-9.3.0.eb`)
* [x] `patchelf-0.10-GCCcore-9.3.0.eb` (replaced with `patchelf-0.12-GCCcore-9.3.0.eb`, see ~~#11173~~)
* [x] `ELPA-2019.11.001-foss-2020a.eb` + `ELPA-2019.11.001-intel-2020a.eb` (~~#11343~~)
* [x] `IRkernel-1.1-foss-2020a-R-3.6.3-Python-3.8.2.eb` (~~#11344~~)
* [x] `Libint-2.6.0-gompi-2020a.eb` -> `Libint-2.6.0-gompi-2020a-lmax-6-cp2k.eb` (~~#11345~~)
* [x] `libxsmm-1.15-foss-2020a.eb` -> `libxsmm-1.16.1-GCC-9.3.0.eb` (~~#11346~~)
* [x] `mpifileutils-0.10-gompi-2020a.eb` + `mpifileutils-0.10-iimpi-2020a.eb` (~~#11347~~)
  * incl. `libcircle-0.3-gompi-2020a.eb` + `libcircle-0.3-iimpi-2020a.eb`
* [x] `ncurses-6.2.eb` (part of ~~#11332~~)
* [x] `OSU-Micro-Benchmarks-5.6.2-*-2020a.eb` -> `OSU-Micro-Benchmarks-5.6.3-*-2020a.eb` (~~#11348~~)
* [x] `MUMmer-3.23-GCCcore-9.3.0.eb` (~~#11349~~)
* [x] `MUMmer-4.0.0beta2-GCCcore-9.3.0.eb` (~~#11350~~)
* [x] `OpenImageIO-2.1.12.0-gompi-2020a.eb` + `OpenImageIO-2.1.12.0-iimpi-2020a.eb` (~~#11351~~)
* [x] `ParMETIS-4.0.3-gompi-2020a.eb` + `ParMETIS-4.0.3-iimpi-2020a.eb` (~~#11352~~)
* [x] `picard-2.22.1-Java-11.eb` (~~#11353~~)
* [x] `Valgrind-3.15.0-*-2020a.eb` -> `Valgrind-3.16.1-*-2020a.eb` (~~#11354~~)

**Comment by boegel** [comment]
All done! \o/
