### ISSUE TITLE
some builds work on SL5, not on SL6 (EB v1.10)

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-easyconfigs#638]
Various builds are known to work on SL5, but not on SL6. This issue is intended to group those together, to keep track of what needs to be fixed.
- [ ] cairo: #639 (+ NCL/6.0.0 because of dep)
- [x] FDTD Solutions: #640
- [ ] HH-suite: #414 (+ HPCBIOS_BioInfo because of dep)
- [ ] CLHEP/VTK: #641 (+ DOLFIN, GATE because of dep)
- [ ] XML-LibXML: #643 (+ XML-Simple because of dep)
- [ ] Sphinx: #644
- [x] ~~PLINK #645 (fixed in #594)~~

**Comment by Micket** [comment]
Long since outdated/resolved
